export interface StateInfo {
  code: string;
  name: string;
  tin: string;
}

export const INDIAN_STATES: Record<string, StateInfo> = {
  "01": { code: "01", name: "Jammu and Kashmir", tin: "01" },
  "02": { code: "02", name: "Himachal Pradesh", tin: "02" },
  "03": { code: "03", name: "Punjab", tin: "03" },
  "04": { code: "04", name: "Chandigarh", tin: "04" },
  "05": { code: "05", name: "Uttarakhand", tin: "05" },
  "06": { code: "06", name: "Haryana", tin: "06" },
  "07": { code: "07", name: "Delhi", tin: "07" },
  "08": { code: "08", name: "Rajasthan", tin: "08" },
  "09": { code: "09", name: "Uttar Pradesh", tin: "09" },
  "10": { code: "10", name: "Bihar", tin: "10" },
  "11": { code: "11", name: "Sikkim", tin: "11" },
  "12": { code: "12", name: "Arunachal Pradesh", tin: "12" },
  "13": { code: "13", name: "Nagaland", tin: "13" },
  "14": { code: "14", name: "Manipur", tin: "14" },
  "15": { code: "15", name: "Mizoram", tin: "15" },
  "16": { code: "16", name: "Tripura", tin: "16" },
  "17": { code: "17", name: "Meghalaya", tin: "17" },
  "18": { code: "18", name: "Assam", tin: "18" },
  "19": { code: "19", name: "West Bengal", tin: "19" },
  "20": { code: "20", name: "Jharkhand", tin: "20" },
  "21": { code: "21", name: "Odisha", tin: "21" },
  "22": { code: "22", name: "Chhattisgarh", tin: "22" },
  "23": { code: "23", name: "Madhya Pradesh", tin: "23" },
  "24": { code: "24", name: "Gujarat", tin: "24" },
  "25": { code: "25", name: "Daman and Diu", tin: "25" },
  "26": { code: "26", name: "Dadra and Nagar Haveli", tin: "26" },
  "27": { code: "27", name: "Maharashtra", tin: "27" },
  "28": { code: "28", name: "Andhra Pradesh (Old)", tin: "28" },
  "29": { code: "29", name: "Karnataka", tin: "29" },
  "30": { code: "30", name: "Goa", tin: "30" },
  "31": { code: "31", name: "Lakshadweep", tin: "31" },
  "32": { code: "32", name: "Kerala", tin: "32" },
  "33": { code: "33", name: "Tamil Nadu", tin: "33" },
  "34": { code: "34", name: "Puducherry", tin: "34" },
  "35": { code: "35", name: "Andaman and Nicobar Islands", tin: "35" },
  "36": { code: "36", name: "Telangana", tin: "36" },
  "37": { code: "37", name: "Andhra Pradesh", tin: "37" },
  "38": { code: "38", name: "Ladakh", tin: "38" },
  "97": { code: "97", name: "Other Territory", tin: "97" },
  "96": { code: "96", name: "Foreign Country", tin: "96" },
};

export const GST_UQC_UNITS = [
  { code: "BAG", name: "BAGS" },
  { code: "BAL", name: "BALE" },
  { code: "BDL", name: "BUNDLES" },
  { code: "BKL", name: "BUCKLES" },
  { code: "BOU", name: "BILLIONS OF UNITS" },
  { code: "BOX", name: "BOX" },
  { code: "BTL", name: "BOTTLES" },
  { code: "BUN", name: "BUNCHES" },
  { code: "CAN", name: "CANS" },
  { code: "CBM", name: "CUBIC METERS" },
  { code: "CCM", name: "CUBIC CENTIMETERS" },
  { code: "CMS", name: "CENTIMETERS" },
  { code: "CTN", name: "CARTONS" },
  { code: "DOZ", name: "DOZENS" },
  { code: "DRM", name: "DRUMS" },
  { code: "GMS", name: "GRAMS" },
  { code: "GRS", name: "GROSS" },
  { code: "GYD", name: "GROSS YARDS" },
  { code: "KGS", name: "KILOGRAMS" },
  { code: "KLR", name: "KILOLITRE" },
  { code: "KME", name: "KILOMETRE" },
  { code: "MLT", name: "MILLILITRE" },
  { code: "MTR", name: "METERS" },
  { code: "MTS", name: "METRIC TON" },
  { code: "NOS", name: "NUMBERS" },
  { code: "PAC", name: "PACKS" },
  { code: "PCS", name: "PIECES" },
  { code: "PRS", name: "PAIRS" },
  { code: "QTL", name: "QUINTAL" },
  { code: "ROL", name: "ROLLS" },
  { code: "SET", name: "SETS" },
  { code: "SQF", name: "SQUARE FEET" },
  { code: "SQM", name: "SQUARE METERS" },
  { code: "SQY", name: "SQUARE YARDS" },
  { code: "TBS", name: "TABLETS" },
  { code: "TGM", name: "TEN GRAMS" },
  { code: "THD", name: "THOUSANDS" },
  { code: "TON", name: "TONNES" },
  { code: "TUB", name: "TUBES" },
  { code: "UGS", name: "US GALLONS" },
  { code: "UNT", name: "UNITS" },
  { code: "YDS", name: "YARDS" },
  { code: "OTH", name: "OTHERS" },
];

export const GST_RATES = [0, 0.1, 0.25, 1.5, 3, 5, 6, 7.5, 12, 18, 28];

export const PRE_SEEDED_GROUPS = [
  // Primary Groups
  { name: "Primary", parent: null, nature: "Primary", isPrimary: true },
  { name: "Capital Account", parent: "Primary", nature: "Liabilities", isPrimary: true },
  { name: "Loans (Liability)", parent: "Primary", nature: "Liabilities", isPrimary: true },
  { name: "Current Liabilities", parent: "Primary", nature: "Liabilities", isPrimary: true },
  { name: "Fixed Assets", parent: "Primary", nature: "Assets", isPrimary: true },
  { name: "Current Assets", parent: "Primary", nature: "Assets", isPrimary: true },
  { name: "Investments", parent: "Primary", nature: "Assets", isPrimary: true },
  { name: "Sales Accounts", parent: "Primary", nature: "Income", isPrimary: true },
  { name: "Purchase Accounts", parent: "Primary", nature: "Expenses", isPrimary: true },
  { name: "Direct Incomes", parent: "Primary", nature: "Income", isPrimary: true },
  { name: "Indirect Incomes", parent: "Primary", nature: "Income", isPrimary: true },
  { name: "Direct Expenses", parent: "Primary", nature: "Expenses", isPrimary: true },
  { name: "Indirect Expenses", parent: "Primary", nature: "Expenses", isPrimary: true },
  { name: "Duties & Taxes", parent: "Current Liabilities", nature: "Liabilities", isPrimary: false },
  { name: "Sundry Creditors", parent: "Current Liabilities", nature: "Liabilities", isPrimary: false },
  { name: "Provisions", parent: "Current Liabilities", nature: "Liabilities", isPrimary: false },
  { name: "Bank Accounts", parent: "Current Assets", nature: "Assets", isPrimary: false },
  { name: "Cash-in-hand", parent: "Current Assets", nature: "Assets", isPrimary: false },
  { name: "Sundry Debtors", parent: "Current Assets", nature: "Assets", isPrimary: false },
  { name: "Stock-in-hand", parent: "Current Assets", nature: "Assets", isPrimary: false },
  { name: "Loans & Advances (Asset)", parent: "Current Assets", nature: "Assets", isPrimary: false },
  { name: "Deposits (Asset)", parent: "Current Assets", nature: "Assets", isPrimary: false },
  { name: "Bank OD/CC A/c", parent: "Loans (Liability)", nature: "Liabilities", isPrimary: false },
  { name: "Secured Loans", parent: "Loans (Liability)", nature: "Liabilities", isPrimary: false },
  { name: "Unsecured Loans", parent: "Loans (Liability)", nature: "Liabilities", isPrimary: false },
  { name: "Reserves & Surplus", parent: "Capital Account", nature: "Liabilities", isPrimary: false },
];

export const PRE_SEEDED_LEDGERS = [
  { name: "Cash", group: "Cash-in-hand", openingType: "Dr" },
  { name: "Profit & Loss A/c", group: "Primary", openingType: "Cr" },
  { name: "Sales - Intra State (CGST + SGST)", group: "Sales Accounts", openingType: "Cr" },
  { name: "Sales - Inter State (IGST)", group: "Sales Accounts", openingType: "Cr" },
  { name: "Sales - Exempt / Nil-Rated", group: "Sales Accounts", openingType: "Cr" },
  { name: "Purchase - Intra State", group: "Purchase Accounts", openingType: "Dr" },
  { name: "Purchase - Inter State", group: "Purchase Accounts", openingType: "Dr" },
  { name: "CGST Input", group: "Duties & Taxes", openingType: "Dr" },
  { name: "SGST Input", group: "Duties & Taxes", openingType: "Dr" },
  { name: "IGST Input", group: "Duties & Taxes", openingType: "Dr" },
  { name: "CGST Output", group: "Duties & Taxes", openingType: "Cr" },
  { name: "SGST Output", group: "Duties & Taxes", openingType: "Cr" },
  { name: "IGST Output", group: "Duties & Taxes", openingType: "Cr" },
  { name: "Cess Input", group: "Duties & Taxes", openingType: "Dr" },
  { name: "Cess Output", group: "Duties & Taxes", openingType: "Cr" },
  { name: "Round Off", group: "Indirect Expenses", openingType: "Dr" },
  { name: "Discount Given", group: "Indirect Expenses", openingType: "Dr" },
  { name: "Discount Received", group: "Indirect Incomes", openingType: "Cr" },
  { name: "Freight Charges", group: "Direct Expenses", openingType: "Dr" },
];
